---
version: "3"

tasks:
  build:
    cmds:
      - go mod tidy
      - go generate ./...
      - goreleaser --snapshot --skip-publish --rm-dist

  install:
    cmds:
      - task: build
      - cf install-plugin dist/darwin_darwin_amd64/cf-reverse-service-lookup-plugin -f

  uninstall:
    cmds:
      - cf uninstall-plugin cf-reverse-service-lookup-plugin

  test:
    cmds:
      - task: install
      - cf rsl -s db8dba61-32c7-4834-b94b-b3d61240d47b --format json | jq '.'
      - cf rsl -s db8dba61-32c7-4834-b94b-b3d61240d47b --format table --format json
      - cf rsl -s db8dba61-32c7-4834-b94b-b3d61240d47b -s db8dba61-32c7-4834-b94b-b3d61240d47b
      - task: uninstall
