---
version: "3"

tasks:
  build:
    cmds:
      - go mod tidy
      - go generate ./...
      - goreleaser --snapshot --skip-publish --rm-dist

  install:
    cmds:
      - task: build
      - cf install-plugin dist/darwin_darwin_amd64/cf-reverse-service-lookup-plugin -f

  uninstall:
    cmds:
      - cf uninstall-plugin cf-reverse-service-lookup-plugin

  test:
    cmds:
      - task: install
      - cf rsl -s 8891ec47-4041-496b-af36-10d89c9513a6
      - cf rsl -s 8891ec47-4041-496b-af36-10d89c9513a6 --format json | jq '.'
      - cf rsl -s 8891ec47-4041-496b-af36-10d89c9513a6 --format table --format plain-text --format json
      - cf rsl -s 8891ec47-4041-496b-af36-10d89c9513a6 -s 8891ec47-4041-496b-af36-10d89c9513a6
      - task: uninstall
